name: Build
on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    permissions:
      pull-requests: write
      checks: write
      contents: read
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: |
          $sonarBeginArgs = @(
            "begin",
            "/k:enelramon_AdventureAdmin",
            "/o:enelramon",
            "/d:sonar.token=${{ secrets.SONAR_TOKEN }}",
            "/d:sonar.host.url=https://sonarcloud.io",
            "/d:sonar.exclusions=**/AdventureAdmin.Data/**/*"
          )
          
          # Configuración adicional para PRs
          if ("${{ github.event_name }}" -eq "pull_request") {
            $sonarBeginArgs += "/d:sonar.pullrequest.key=${{ github.event.pull_request.number }}"
            $sonarBeginArgs += "/d:sonar.pullrequest.branch=${{ github.head_ref }}"
            $sonarBeginArgs += "/d:sonar.pullrequest.base=${{ github.base_ref }}"
            $sonarBeginArgs += "/d:sonar.scm.provider=git"
          }
          
          .\.sonar\scanner\dotnet-sonarscanner @sonarBeginArgs
          dotnet build AdventureAdmin.slnx
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"